### ISSUE TITLE
No older versions listed in "Install another version..." menu

### ISSUE THREAD

**Issue by mk-fhg** [microsoft/vscode-python-debugger#200]
I have the Python Debugger extension version 2024.0.0 installed.
I need to use Python 3.6.9. Debugging is no longer supported for this Python version.
I need an older version of the debugger.
On the Python Debugger extension page clicking "Uninstall->More actions...->Install another version..." only shows the version 2024.0.0.

I tried this in my main VS Code install (version 1.85), as well as fresh portable versions of VS code (versions 1.86 and 1.85).

I'm running Ubuntu 18.04.6 LTS.

**Comment by karthiknadig** [comment]
This should be addressed now, please re-start your VS Code:
![image](https://github.com/microsoft/vscode-python-debugger/assets/3840081/db45d443-bbaf-476a-9e42-01306281419f)

**Comment by mk-fhg** [comment]
The problem is still there for me.
I also treid a completly different PC.
Still, only version 2024.0.0 is shown.
